apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resilient-webserver-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: devops-intern.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: resilient-webserver-service
            port:
              number: 80
