apiVersion: v1
kind: Service
metadata:
  name: resilient-webserver-service
spec:
  selector:
    app: resilient-webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
